// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptrgysnjwlzauzxllixn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0cmd5c25qd2x6YXV6eGxsaXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MTAwMTMsImV4cCI6MjA3MTE4NjAxM30.HrZzgmGzCAUd8Q_KUUwdRyp3XPY18kOtFH8g6NfJAjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});